name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: issenn/flowzone/.github/workflows/flowzone.yml@feat-issenn
    secrets: inherit
